const ASSETS = {
  health: 'Geo Assets/Al_health_facilities.csv',
  water: 'Geo Assets/All_water_Projects.csv',
  schools: 'Geo Assets/Schools.json',
  localities: 'Geo Assets/Sudan_Localities/Sudan_Khartoum_Localities.geojson',
  populationOverrides: 'Geo Assets/Sudan_Localities/population_overrides.json',
  humanitarianIndicators: 'Geo Assets/Sudan_Localities/humanitarian_indicators.json',
  metadata: 'metadata.json',
  authoritySchools: 'Geo Assets/External/schools-authority-gezira.json',
  educationReference: 'Geo Assets/External/hotosm-education-gezira.geojson',
  waterReference: 'Geo Assets/External/hotosm-water-reference-gezira.geojson'
};
const STATE_OPTIONS = [
  { value: 'Gezira', label: 'Al Gezira', test: value => /gezira|gazira|jazeera|jazirah|الجزيرة/i.test(value || '') },
  { value: 'Blue Nile', label: 'Blue Nile', test: value => /blue\s*nile/i.test(value || '') },
  { value: 'White Nile', label: 'White Nile', test: value => /white\s*nile/i.test(value || '') },
  { value: 'Kassala', label: 'Kassala', test: value => /kassala/i.test(value || '') },
  { value: 'Gedaref', label: 'Gadaref', test: value => /gadaref|gedaref|qadarif|gadarif/i.test(value || '') }
];

const urlState = new URLSearchParams(location.search);
const state = { health: [], water: [], schools: [], authoritySchools: [], educationReference: [], waterReference: [], localities: null, metadata: null, geziraGeometries: [], selectedLocalityCodes: (urlState.get('locality') || '').split(',').filter(Boolean), selectedStates: (urlState.get('states') || '').split(',').filter(Boolean).length ? urlState.get('states').split(',').filter(Boolean) : ['Gezira'], search: urlState.get('search') || '', schoolLoaded: false, educationReferenceLoaded: false, waterReferenceLoaded: false, labelsVisible: urlState.get('labels') !== 'false', quality: { healthInvalid: 0, waterInvalid: 0, schoolsOutside: 0 }, language: 'en', choroplethMode: urlState.get('view') || 'population', humanitarianIndicators: {} };
const layers = {};
let localityPopulationMaximum = 1;
let idpMaximum = 1;
const statePopulationMaximums = {};
const stateTotalPopulations = {};
const extendedTranslations = { en: { localityLabels: 'Locality labels', educationReference: 'Education reference (HOT/OSM)', waterReference: 'Water infrastructure reference (HOT/OSM)', hotOsm: 'Humanitarian OpenStreetMap Team / OpenStreetMap', authoritySchools: 'Authority school records', students: 'Students enrolled', search: 'Search facilities and projects', searchPlaceholder: 'Search by name or ID', searchHint: 'Type a facility name, project ID, or locality to filter the map instantly.', localityProfile: 'Locality profile', facilityRate: 'Health facilities per 10,000', allLocalitiesProfile: 'All selected localities', dataQuality: 'Data quality', invalidCoordinates: 'records excluded for invalid coordinates', export: 'Export CSV', share: 'Share view', print: 'Print', shared: 'Share link copied', idps: 'IDPs (IOM DTM)', returnees: 'Returnees (IOM DTM)', needsSeverity: 'Needs severity (JIAF, 1-5)', healthPin: 'Health people in need', washPin: 'WASH people in need', choroplethMode: 'Shade localities by', viewPopulation: 'Population', viewSeverity: 'Humanitarian severity', viewIdps: 'IDP presence', idpsProfile: 'IDPs in area', returneesProfile: 'Returnees in area', idpsSourceLabel: 'IDPs & returnees', iomDtmSource: 'IOM Displacement Tracking Matrix (DTM), Jul 2026', needsSourceLabel: 'Needs severity & PiN', jiafSource: 'OCHA Sudan / JIAF, 2026', shareOfState: 'Share of state population' }, ar: { localityLabels: 'تسميات المحليات', educationReference: 'مرجع مرافق التعليم (HOT/OSM)', waterReference: 'مرجع البنية التحتية للمياه (HOT/OSM)', hotOsm: 'فريق OpenStreetMap الإنساني / OpenStreetMap', authoritySchools: 'سجلات المدارس الرسمية', students: 'الطلاب المسجلون', search: 'البحث في المرافق والمشاريع', searchPlaceholder: 'ابحث بالاسم أو المعرف', searchHint: 'اكتب اسم المرفق أو معرف المشروع أو اسم المحلية لتصفية الخريطة فوراً.', localityProfile: 'ملف المحلية', facilityRate: 'مرافق صحية لكل 10,000', allLocalitiesProfile: 'كل المحليات المحددة', dataQuality: 'جودة البيانات', invalidCoordinates: 'سجل مستبعد لإحداثيات غير صالحة', export: 'تصدير CSV', share: 'مشاركة العرض', print: 'طباعة', shared: 'تم نسخ رابط المشاركة', idps: 'النازحون (IOM DTM)', returnees: 'العائدون (IOM DTM)', needsSeverity: 'شدة الاحتياج (JIAF، 1-5)', healthPin: 'المحتاجون للصحة', washPin: 'المحتاجون للمياه والصرف الصحي', choroplethMode: 'تلوين المحليات حسب', viewPopulation: 'السكان', viewSeverity: 'شدة الاحتياج الإنساني', viewIdps: 'وجود النازحين', idpsProfile: 'النازحون في المنطقة', returneesProfile: 'العائدون في المنطقة', idpsSourceLabel: 'النازحون والعائدون', iomDtmSource: 'مصفوفة تتبع النزوح (DTM) التابعة للمنظمة الدولية للهجرة، يوليو 2026', needsSourceLabel: 'شدة الاحتياج وعدد المحتاجين', jiafSource: 'أوتشا السودان / JIAF، 2026', shareOfState: 'النسبة من سكان الولاية' } };
const dataQualityText = { en: { invalid: 'invalid-coordinate records excluded', outside: 'school records outside Al Gezira excluded' }, ar: { invalid: 'سجلات مستبعدة لإحداثيات غير صالحة', outside: 'سجلات مدارس خارج الجزيرة مستبعدة' } };
const translations = {
  en: { intelligence: 'Facilities intelligence', title: 'Gezira Facilities Dashboard', dark: 'Dark', healthFacilities: 'Health facilities', waterProjects: 'Water projects', schools: 'Schools', availableEstimates: 'From available estimates', explore: 'Explore', mapLayers: 'Map layers', displayedLayers: 'Displayed layers', localityBoundaries: 'Locality boundaries', localityLabels: 'Locality labels', loadsOnDemand: 'loads on demand', localityFilter: 'Locality', allLocalities: 'All localities', legend: 'Legend', healthFacility: 'Health facility', waterProject: 'Water project', school: 'School', localityBoundary: 'Locality boundary', reportedPopulation: 'Reported population', populationNotReported: 'Population not reported', low: 'Low', high: 'High', facilityCoverage: 'Facility coverage', fitResults: 'Fit results', mappedFacilities: 'Mapped facilities', mappedProjects: 'Mapped projects', enableSchools: 'Enable layer to load', schoolsWithin: 'Within Al Gezira localities', state: 'State', locality: 'Locality', projectId: 'Project ID', donor: 'Donor', estimatedBeneficiaries: 'Estimated beneficiaries', city: 'City', operator: 'Operator', capacity: 'Capacity', population: 'Population', notReported: 'Not reported', updated: 'Updated from source files', dataSources: 'Data sources', healthPillar: 'Health Pillar', rrPillar: 'R&R Pillar', gisUnit: 'GIS Unit data assets', populationSource: 'UNFPA / HDX, 2024', results: (health, water) => `${health.toLocaleString()} health facilities and ${water.toLocaleString()} water projects in view` },
  ar: { intelligence: 'معلومات المرافق', title: 'لوحة مرافق الجزيرة', dark: 'داكن', healthFacilities: 'المرافق الصحية', waterProjects: 'مشاريع المياه', schools: 'المدارس', availableEstimates: 'من التقديرات المتاحة', explore: 'استكشاف', mapLayers: 'طبقات الخريطة', displayedLayers: 'الطبقات المعروضة', localityBoundaries: 'حدود المحليات', localityLabels: 'تسميات المحليات', loadsOnDemand: 'تحميل عند الطلب', localityFilter: 'المحلية', allLocalities: 'كل المحليات', legend: 'المفتاح', healthFacility: 'مرفق صحي', waterProject: 'مشروع مياه', school: 'مدرسة', localityBoundary: 'حدود المحلية', reportedPopulation: 'السكان المبلغ عنهم', populationNotReported: 'بيانات السكان غير متاحة', low: 'منخفض', high: 'مرتفع', facilityCoverage: 'تغطية المرافق', fitResults: 'ملاءمة العرض', mappedFacilities: 'مرافق محددة على الخريطة', mappedProjects: 'مشاريع محددة على الخريطة', enableSchools: 'فعّل الطبقة للتحميل', schoolsWithin: 'ضمن محليات الجزيرة', state: 'الولاية', locality: 'المحلية', projectId: 'معرف المشروع', donor: 'الجهة المانحة', estimatedBeneficiaries: 'المستفيدون التقديريون', city: 'المدينة', operator: 'المشغل', capacity: 'السعة', population: 'السكان', notReported: 'غير متاح', updated: 'تم التحديث من ملفات المصدر', dataSources: 'مصادر البيانات', healthPillar: 'ركيزة الصحة', rrPillar: 'ركيزة التعافي والقدعة على الصمود', gisUnit: 'أصول بيانات وحدة نظم المعلومات الجغرافية', populationSource: 'صندوق الأمم المتحدة للسكان / HDX، 2024', results: (health, water) => `${health.toLocaleString()} مرفقاً صحياً و${water.toLocaleString()} مشروع مياه في العرض` }
};
function t(key) { return translations[state.language][key] || extendedTranslations[state.language][key] || key; }
const map = L.map('map', { preferCanvas: true, zoomControl: false }).setView([15.4, 33.2], 6);
L.control.zoom({ position: 'bottomright' }).addTo(map);
const baseMap = L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Light_Gray_Base/MapServer/tile/{z}/{y}/{x}', { maxZoom: 16, attribution: 'Tiles &copy; Esri' }).addTo(map);
const baseMapUrls = { light: 'https://server.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Light_Gray_Base/MapServer/tile/{z}/{y}/{x}', dark: 'https://server.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Dark_Gray_Base/MapServer/tile/{z}/{y}/{x}' };

function updateUrl() { const query = new URLSearchParams(); if (state.selectedLocalityCodes.length) query.set('locality', state.selectedLocalityCodes.join(',')); if (state.selectedStates.length !== STATE_OPTIONS.length) query.set('states', state.selectedStates.join(',')); if (state.search) query.set('search', state.search); if (!state.labelsVisible) query.set('labels', 'false'); if (state.choroplethMode !== 'population') query.set('view', state.choroplethMode); history.replaceState(null, '', `${location.pathname}${query.size ? `?${query}` : ''}`); }
function setTheme(theme) { document.documentElement.dataset.theme = theme; document.querySelector('#theme-toggle').checked = theme === 'dark'; baseMap.setUrl(baseMapUrls[theme]); localStorage.setItem('gezira-dashboard-theme', theme); }
const preferredTheme = localStorage.getItem('gezira-dashboard-theme') || 'light';
setTheme(preferredTheme);
function setLanguage(language) { state.language = language; document.documentElement.lang = language; document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr'; document.querySelectorAll('[data-i18n]').forEach(element => { element.textContent = t(element.dataset.i18n); }); document.querySelector('#search-filter').placeholder = t('searchPlaceholder'); document.querySelectorAll('[data-language]').forEach(button => button.classList.toggle('active', button.dataset.language === language)); if (state.localities) { populateLocalityFilter(); layers.localities.clearLayers(); layers.localities.addData(state.localities); updateDashboard(); document.querySelector('#data-status').textContent = t('updated'); } localStorage.setItem('gezira-dashboard-language', language); }

function parseCsv(text) {
  const rows = []; let row = []; let value = ''; let quoted = false;
  for (let index = 0; index < text.length; index += 1) {
    const character = text[index];
    if (character === '"') { if (quoted && text[index + 1] === '"') { value += character; index += 1; } else quoted = !quoted; }
    else if (character === ',' && !quoted) { row.push(value.trim()); value = ''; }
    else if ((character === '\n' || character === '\r') && !quoted) { if (character === '\r' && text[index + 1] === '\n') index += 1; row.push(value.trim()); if (row.some(Boolean)) rows.push(row); row = []; value = ''; }
    else value += character;
  }
  if (value || row.length) { row.push(value.trim()); rows.push(row); }
  const [headers, ...records] = rows;
  return records.map(record => Object.fromEntries(headers.map((header, index) => [header, record[index] ?? ''])));
}

function coordinate(value) { const parsed = Number.parseFloat(String(value).replace(',', '.')); return Number.isFinite(parsed) ? parsed : null; }
function validPoint(latitude, longitude) { return latitude !== null && longitude !== null && Math.abs(latitude) <= 90 && Math.abs(longitude) <= 180; }
function number(value) { return Number.parseFloat(String(value || '').replace(/,/g, '')) || 0; }
function safe(value) { const node = document.createElement('span'); node.textContent = value || 'Not available'; return node.innerHTML; }
function normalizedName(value) { return String(value || '').toLocaleLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[\u064B-\u065F\u0670]/g, '').replace(/[^\p{L}\p{N}]/gu, ''); }
function isGezira(value) { return /gezira|gazira|jazeera|jazirah|الجزيرة/i.test(value || ''); }
function matchingStateOption(value) { return STATE_OPTIONS.find(option => option.test(value)); }
function isKnownState(value) { return Boolean(matchingStateOption(value)); }
function isSelectedState(value) { const option = matchingStateOption(value); return option ? state.selectedStates.includes(option.value) : false; }
function stateGroupKey(value) { return matchingStateOption(value)?.value || null; }
function pointInRing(longitude, latitude, ring) { let inside = false; for (let index = 0, previous = ring.length - 1; index < ring.length; previous = index, index += 1) { const [currentLongitude, currentLatitude] = ring[index]; const [previousLongitude, previousLatitude] = ring[previous]; const intersects = (currentLatitude > latitude) !== (previousLatitude > latitude) && longitude < ((previousLongitude - currentLongitude) * (latitude - currentLatitude)) / (previousLatitude - currentLatitude) + currentLongitude; if (intersects) inside = !inside; } return inside; }
function pointInPolygon(longitude, latitude, polygon) { return pointInRing(longitude, latitude, polygon[0]) && !polygon.slice(1).some(ring => pointInRing(longitude, latitude, ring)); }
function isWithinGeziraLocality(longitude, latitude) { return state.geziraGeometries.some(geometry => geometry.type === 'Polygon' ? pointInPolygon(longitude, latitude, geometry.coordinates) : geometry.type === 'MultiPolygon' && geometry.coordinates.some(polygon => pointInPolygon(longitude, latitude, polygon))); }
function selectedLocalities() { return state.localities?.features.filter(feature => state.selectedLocalityCodes.includes(feature.properties.hrpcode)) || []; }
function isWithinSelectedLocality(longitude, latitude) { const features = selectedLocalities(); if (!features.length) return true; return features.some(feature => feature.geometry.type === 'Polygon' ? pointInPolygon(longitude, latitude, feature.geometry.coordinates) : feature.geometry.coordinates.some(polygon => pointInPolygon(longitude, latitude, polygon))); }
function summarizeSelection(labels, allCount, allLabel, noneLabel) { if (!labels.length) return noneLabel; if (labels.length === allCount) return allLabel; if (labels.length <= 2) return labels.join(', '); return `${labels.length} selected`; }
function updateDropdownSummary(dropdownId, items, selectedValues, allLabel, noneLabel) { const toggle = document.querySelector(`#${dropdownId} .dropdown-toggle`); const selectedLabels = items.filter(item => selectedValues.includes(item.value)).map(item => item.label); toggle.textContent = summarizeSelection(selectedLabels, items.length, allLabel, noneLabel); }
function buildDropdownPanel(dropdownId, items, getSelected, onChange, allLabel, noneLabel) {
  const panel = document.querySelector(`#${dropdownId} .dropdown-panel`);
  panel.replaceChildren(...items.map(item => {
    const label = document.createElement('label'); label.className = 'dropdown-option'; label.setAttribute('role', 'option');
    const checkbox = document.createElement('input'); checkbox.type = 'checkbox'; checkbox.value = item.value; checkbox.checked = getSelected().includes(item.value);
    checkbox.addEventListener('change', () => { const values = Array.from(panel.querySelectorAll('input[type=checkbox]:checked')).map(box => box.value); onChange(values); updateDropdownSummary(dropdownId, items, values, allLabel, noneLabel); });
    const span = document.createElement('span'); span.textContent = item.label;
    label.append(checkbox, span); return label;
  }));
  updateDropdownSummary(dropdownId, items, getSelected(), allLabel, noneLabel);
}
function closeDropdowns(except) { document.querySelectorAll('.dropdown-multiselect.open').forEach(el => { if (el !== except) { el.classList.remove('open'); el.querySelector('.dropdown-panel').hidden = true; el.querySelector('.dropdown-toggle').setAttribute('aria-expanded', 'false'); } }); }
document.querySelectorAll('.dropdown-multiselect').forEach(dropdown => {
  const toggle = dropdown.querySelector('.dropdown-toggle'); const panel = dropdown.querySelector('.dropdown-panel');
  toggle.addEventListener('click', () => { const isOpen = dropdown.classList.contains('open'); closeDropdowns(); dropdown.classList.toggle('open', !isOpen); panel.hidden = isOpen; toggle.setAttribute('aria-expanded', String(!isOpen)); });
});
document.addEventListener('click', event => { document.querySelectorAll('.dropdown-multiselect.open').forEach(dropdown => { if (!dropdown.contains(event.target)) closeDropdowns(); }); });
function populateLocalityFilter() { const features = state.localities.features.filter(feature => isSelectedState(feature.properties.state_en)); const validCodes = new Set(features.map(feature => feature.properties.hrpcode)); state.selectedLocalityCodes = state.selectedLocalityCodes.filter(code => validCodes.has(code)); const items = features.map(feature => { const name = state.language === 'ar' ? feature.properties.loc_name : feature.properties.loc_en; const stateName = state.language === 'ar' ? feature.properties.state : feature.properties.state_en; const label = isGezira(feature.properties.state_en) ? name : `${name} (${stateName})`; return { value: feature.properties.hrpcode, label }; }); buildDropdownPanel('locality-filter-dropdown', items, () => state.selectedLocalityCodes, values => { state.selectedLocalityCodes = values; layers.localities.setStyle(localityStyle); layers.localityHighlight.clearLayers(); selectedLocalities().forEach(feature => layers.localityHighlight.addData(feature)); layers.localityHighlight.bringToFront(); updateDashboard(); fitResults(); }, t('allLocalities'), t('allLocalities')); }
function populateStateFilter() { const items = STATE_OPTIONS.map(option => ({ value: option.value, label: option.label })); buildDropdownPanel('state-filter-dropdown', items, () => state.selectedStates, values => { state.selectedStates = values; populateLocalityFilter(); layers.localities.clearLayers(); layers.localities.addData(state.localities); layers.localityHighlight.clearLayers(); selectedLocalities().forEach(feature => layers.localityHighlight.addData(feature)); if (!state.labelsVisible) layers.localities.eachLayer(layer => layer.closeTooltip()); updateDashboard(); updateUrl(); }, 'All states', 'No states selected'); }
function matchesStateFilter(record) { if (!state.selectedStates.length) return false; const value = String(record.state || record.locality || '').trim(); return state.selectedStates.some(key => STATE_OPTIONS.find(option => option.value === key)?.test(value)); }
function matchesSearch(record) { const query = state.search.trim().toLocaleLowerCase(); return !query || [record.name, record.id, record.state, record.locality, record.donor].filter(Boolean).join(' ').toLocaleLowerCase().includes(query); }
function indicatorsFor(feature) { return state.humanitarianIndicators[feature.properties.hrpcode]; }
function localityStyle(feature) {
  const selected = state.selectedLocalityCodes.includes(feature.properties.hrpcode);
  if (state.choroplethMode === 'severity') {
    const severity = indicatorsFor(feature)?.severity;
    const outline = { color: selected ? '#006eb5' : severity ? '#8a2f22' : '#89949b', weight: selected ? 3 : 1.4, dashArray: selected ? null : '5 4' };
    if (!severity) return { ...outline, fillColor: '#e4e8eb', fillOpacity: selected ? .82 : .72 };
    const ratio = Math.min(severity / 5, 1);
    return { ...outline, fillColor: `hsl(8 ${30 + ratio * 60}% ${92 - ratio * 45}%)`, fillOpacity: selected ? .85 : .72 };
  }
  if (state.choroplethMode === 'idps') {
    const idps = indicatorsFor(feature)?.idps || 0;
    const outline = { color: selected ? '#006eb5' : idps > 0 ? '#8a5a00' : '#89949b', weight: selected ? 3 : 1.4, dashArray: selected ? null : '5 4' };
    if (idps <= 0) return { ...outline, fillColor: '#e4e8eb', fillOpacity: selected ? .82 : .72 };
    const ratio = Math.min(idps / idpMaximum, 1);
    return { ...outline, fillColor: `hsl(35 ${30 + ratio * 60}% ${92 - ratio * 45}%)`, fillOpacity: selected ? .85 : .72 };
  }
  const population = number(feature.properties.total_pop); const outline = { color: selected ? '#006eb5' : population <= 0 ? '#89949b' : '#006eb5', weight: selected ? 3 : 1.4, dashArray: selected ? null : '5 4' }; if (population <= 0) return { ...outline, fillColor: '#e4e8eb', fillOpacity: selected ? .82 : .72 }; const groupMax = statePopulationMaximums[stateGroupKey(feature.properties.state_en)] || localityPopulationMaximum; const ratio = Math.min(population / groupMax, 1); return { ...outline, fillColor: `hsl(204 ${26 + ratio * 70}% ${94 - ratio * 48}%)`, fillOpacity: selected ? .82 : .68 };
}
function svgIcon(type) {
  const iconMap = {
    health: 'ocha-icons/Health-facility_40658.svg',
    water: 'ocha-icons/Water-source_40584.svg',
    school: 'ocha-icons/School_40440.svg',
    'education-reference': 'ocha-icons/School_40440.svg',
    'water-reference': 'ocha-icons/Water-source_40584.svg'
  };
  const iconPath = iconMap[type] || iconMap.health;
  return `<img src="${iconPath}" alt="${type}" style="width:100%;height:100%;object-fit:contain;">`;
}
function markerIcon(type) {
  return L.divIcon({ className: '', html: `<div class="facility-marker ${type}">${svgIcon(type)}</div>`, iconSize: [24, 24], iconAnchor: [12, 12] });
}
function popup(type, title, fields) { return `<article class="popup-content"><p>${type}</p><h3>${safe(title)}</h3><dl>${fields.filter(([, value]) => value).map(([label, value]) => `<dt>${safe(label)}</dt><dd>${safe(value)}</dd>`).join('')}</dl></article>`; }

function createCluster(type) { return L.markerClusterGroup({ chunkedLoading: true, chunkInterval: 80, chunkDelay: 20, removeOutsideVisibleBounds: true, spiderfyOnMaxZoom: true, maxClusterRadius: 48, iconCreateFunction: cluster => { const count = cluster.getChildCount(); const size = count < 10 ? 44 : count < 100 ? 50 : 56; return L.divIcon({ html: `<div>${svgIcon(type)}<b>${count}</b></div>`, className: `marker-cluster layer-cluster ${type}`, iconSize: [size, size], iconAnchor: [size / 2, size / 2] }); } }); }
function addHealthMarkers(records) { layers.health.clearLayers(); records.forEach(record => layers.health.addLayer(L.marker([record.latitude, record.longitude], { icon: markerIcon('health'), title: record.name }).bindPopup(popup(t('healthFacility'), record.name, [[t('state'), record.state], [t('locality'), record.locality]])))); }
function addWaterMarkers(records) { layers.water.clearLayers(); records.forEach(record => layers.water.addLayer(L.marker([record.latitude, record.longitude], { icon: markerIcon('water'), title: record.name }).bindPopup(popup(t('waterProject'), record.name, [[t('projectId'), record.id], [t('state'), record.state], [t('locality'), record.locality], [t('donor'), record.donor], [t('estimatedBeneficiaries'), record.beneficiaries ? record.beneficiaries.toLocaleString() : '']])))); }
function addSchoolMarkers(records) { layers.schools.clearLayers(); records.forEach(record => layers.schools.addLayer(L.marker([record.latitude, record.longitude], { icon: markerIcon('school'), title: record.name }).bindPopup(popup(t('school'), record.name, [[t('city'), record.city], [t('operator'), record.operator], [t('capacity'), record.capacity], ['School ID', record.authority?.school_id], ['Type', record.authority?.type], ['Status', record.authority?.status], ['Students', record.authority?.students_total], ['Teachers', record.authority?.teachers], ['Electricity', record.authority?.electricity], ['Water source', record.authority?.potable_water_source]])))); }
function addReferenceMarkers(layer, records, type, heading, fields) { layer.clearLayers(); records.filter(record => isWithinSelectedLocality(record.longitude, record.latitude)).forEach(record => layer.addLayer(L.marker([record.latitude, record.longitude], { icon: markerIcon(type), title: record.name }).bindPopup(popup(heading, record.name, fields(record))))); }

function filteredHealth() { return state.health.filter(record => isWithinSelectedLocality(record.longitude, record.latitude) && matchesSearch(record) && matchesStateFilter(record)); }
function filteredWater() { return state.water.filter(record => isWithinSelectedLocality(record.longitude, record.latitude) && matchesSearch(record) && matchesStateFilter(record)); }
function updateProfile(health, water, schools) { const selected = selectedLocalities(); const scopeFeatures = selected.length ? selected : state.localities.features.filter(feature => isSelectedState(feature.properties.state_en)); const population = scopeFeatures.reduce((sum, feature) => sum + number(feature.properties.total_pop), 0); const idps = scopeFeatures.reduce((sum, feature) => sum + (indicatorsFor(feature)?.idps || 0), 0); const returnees = scopeFeatures.reduce((sum, feature) => sum + (indicatorsFor(feature)?.returnees || 0), 0); const authoritySchools = state.authoritySchools.filter(record => !state.selectedLocalityCodes.length || state.selectedLocalityCodes.includes(record.locality_code)); const educationReferences = state.educationReference.filter(record => isWithinSelectedLocality(record.longitude, record.latitude)); const waterReferences = state.waterReference.filter(record => isWithinSelectedLocality(record.longitude, record.latitude)); const title = selected.length === 1 ? (state.language === 'ar' ? selected[0].properties.loc_name : selected[0].properties.loc_en) : selected.length > 1 ? `${selected.length} ${t('localityFilter')}` : t('allLocalitiesProfile'); document.querySelector('#profile-title').textContent = title; document.querySelector('#profile-population').textContent = population.toLocaleString(); document.querySelector('#profile-idps').textContent = idps.toLocaleString(); document.querySelector('#profile-returnees').textContent = returnees.toLocaleString(); document.querySelector('#profile-health').textContent = health.length.toLocaleString(); document.querySelector('#profile-water').textContent = water.length.toLocaleString(); document.querySelector('#profile-schools').textContent = state.schoolLoaded ? schools.length.toLocaleString() : '-'; document.querySelector('#profile-authority-schools').textContent = authoritySchools.length.toLocaleString(); document.querySelector('#profile-students').textContent = authoritySchools.reduce((sum, record) => sum + number(record.students_total), 0).toLocaleString(); document.querySelector('#profile-education-reference').textContent = state.educationReferenceLoaded ? educationReferences.length.toLocaleString() : '-'; document.querySelector('#profile-water-reference').textContent = state.waterReferenceLoaded ? waterReferences.length.toLocaleString() : '-'; document.querySelector('#profile-rate').textContent = population ? ((health.length / population) * 10000).toFixed(1) : '-'; const invalid = state.quality.healthInvalid + state.quality.waterInvalid; const quality = dataQualityText[state.language]; document.querySelector('#data-quality').textContent = `${t('dataQuality')}: ${invalid} ${quality.invalid}; ${state.quality.schoolsOutside} ${quality.outside}`; }
function updateDashboard() {
  const health = filteredHealth(); const water = filteredWater(); const schools = state.schoolLoaded ? state.schools.filter(record => isWithinSelectedLocality(record.longitude, record.latitude) && matchesSearch(record)) : [];
  addHealthMarkers(health); addWaterMarkers(water); if (state.schoolLoaded) addSchoolMarkers(schools);
  if (state.educationReferenceLoaded) addReferenceMarkers(layers.educationReference, state.educationReference, 'education-reference', t('educationReference'), record => [[t('locality'), record.locality], ['OSM ID', record.id], [t('city'), record.city]]);
  if (state.waterReferenceLoaded) addReferenceMarkers(layers.waterReference, state.waterReference, 'water-reference', t('waterReference'), record => [['Type', record.type], [t('locality'), record.locality], ['OSM ID', record.id]]);
  document.querySelector('#result-summary').textContent = t('results')(health.length, water.length);
  updateProfile(health, water, schools); updateUrl();
}
function setLabelVisibility(visible) { state.labelsVisible = visible; layers.localities.eachLayer(layer => visible ? layer.openTooltip() : layer.closeTooltip()); updateUrl(); }
async function shareView() { try { await navigator.clipboard.writeText(location.href); document.querySelector('#data-status').textContent = t('shared'); } catch { document.querySelector('#data-status').textContent = location.href; } }
function fitResults() { const selected = selectedLocalities(); if (selected.length) { map.fitBounds(L.geoJSON({ type: 'FeatureCollection', features: selected }).getBounds(), { padding: [35, 35], maxZoom: 11 }); return; } const records = [...filteredHealth(), ...filteredWater(), ...(state.schoolLoaded ? state.schools : [])]; if (records.length) map.fitBounds(L.latLngBounds(records.map(record => [record.latitude, record.longitude])), { padding: [35, 35], maxZoom: 11 }); }

async function fetchAsset(path, parser = response => response.json()) { const response = await fetch(encodeURI(path)); if (!response.ok) throw new Error(`${path} could not be loaded (${response.status})`); return parser(response); }
async function loadSchools() { if (state.schoolLoaded) return; const geojson = await fetchAsset(ASSETS.schools); const authorityByName = new Map(state.authoritySchools.flatMap(record => [[normalizedName(record.name_en), record], [normalizedName(record.name_ar), record]]).filter(([name]) => name)); const points = geojson.features.map(feature => { const properties = feature.properties; const nameEn = properties.name_en || properties.name; const nameAr = properties.name_ar; const name = state.language === 'ar' && nameAr ? nameAr : nameEn || nameAr || 'Unnamed school'; return { name, nameEn, nameAr, city: properties.addr_city, operator: properties.operator_t, capacity: properties.capacity_p, authority: authorityByName.get(normalizedName(nameEn)) || authorityByName.get(normalizedName(nameAr)), latitude: feature.geometry?.coordinates?.[1], longitude: feature.geometry?.coordinates?.[0] }; }); const validPoints = points.filter(record => validPoint(record.latitude, record.longitude)); state.quality.schoolsOutside = validPoints.length - validPoints.filter(record => isWithinGeziraLocality(record.longitude, record.latitude)).length; state.schools = validPoints.filter(record => isWithinGeziraLocality(record.longitude, record.latitude)); state.schoolLoaded = true; updateDashboard(); }
async function loadReferenceLayer(name) { if (state[`${name}Loaded`]) return; const geojson = await fetchAsset(ASSETS[name]); state[name] = geojson.features.map(feature => ({ id: feature.properties.id, name: feature.properties.name_en || feature.properties.name || feature.properties.name_ar || 'Unnamed reference', locality: feature.properties.adm2_name, city: feature.properties.addr_city, type: feature.properties.man_made || feature.properties.amenity || 'Reference', latitude: feature.geometry?.coordinates?.[1], longitude: feature.geometry?.coordinates?.[0] })).filter(record => validPoint(record.latitude, record.longitude)); state[`${name}Loaded`] = true; updateDashboard(); }
function setLayerVisibility(name, visible) { if (visible) { if (name === 'schools' || name === 'educationReference' || name === 'waterReference') { map.addLayer(layers[name]); const loader = name === 'schools' ? loadSchools : () => loadReferenceLayer(name); loader().catch(showError); } else { map.addLayer(layers[name]); if (name === 'localities') map.addLayer(layers.localityHighlight); } } else { map.removeLayer(layers[name]); if (name === 'localities') map.removeLayer(layers.localityHighlight); } }
function showError(error) { document.querySelector('#data-status').textContent = 'Some data could not be loaded'; document.querySelector('#result-summary').textContent = error.message; console.error(error); }

async function init() {
  layers.health = createCluster('health'); layers.water = createCluster('water'); layers.schools = createCluster('school'); layers.educationReference = createCluster('education-reference'); layers.waterReference = createCluster('water-reference'); layers.localityHighlight = L.geoJSON(null, { interactive: false, style: { color: '#006eb5', weight: 4, opacity: 1, fillColor: '#b5d5f5', fillOpacity: .24 } }); layers.localities = L.geoJSON(null, { filter: feature => isSelectedState(feature.properties.state_en), style: localityStyle, onEachFeature: (feature, layer) => { const population = number(feature.properties.total_pop); const localityName = state.language === 'ar' ? feature.properties.loc_name : feature.properties.loc_en || 'Locality'; const stateName = state.language === 'ar' ? feature.properties.state : feature.properties.state_en; const indicators = state.humanitarianIndicators[feature.properties.hrpcode]; const stateTotal = stateTotalPopulations[stateGroupKey(feature.properties.state_en)]; const share = population > 0 && stateTotal ? `${((population / stateTotal) * 100).toFixed(1)}%` : ''; layer.bindPopup(popup(t('locality'), `${localityName}, ${stateName}`, [[t('population'), population > 0 ? population.toLocaleString() : t('notReported')], [t('shareOfState'), share], [t('idps'), indicators?.idps ? indicators.idps.toLocaleString() : ''], [t('returnees'), indicators?.returnees ? indicators.returnees.toLocaleString() : ''], [t('needsSeverity'), indicators?.severity ? `${indicators.severity}/5` : ''], [t('healthPin'), indicators?.healthPin ? indicators.healthPin.toLocaleString() : ''], [t('washPin'), indicators?.washPin ? indicators.washPin.toLocaleString() : ''], [t('dataSources'), feature.properties.population_source ? t('populationSource') : '']])); layer.bindTooltip(`<strong>${safe(localityName)}</strong><span>${safe(stateName)}</span>`, { permanent: true, direction: 'center', className: 'locality-label' }); } });
  try {
    const [healthCsv, waterCsv, localities, populationOverrides, metadata, authoritySchools, humanitarianIndicators] = await Promise.all([fetchAsset(ASSETS.health, response => response.text()), fetchAsset(ASSETS.water, response => response.text()), fetchAsset(ASSETS.localities), fetchAsset(ASSETS.populationOverrides), fetchAsset(ASSETS.metadata), fetchAsset(ASSETS.authoritySchools), fetchAsset(ASSETS.humanitarianIndicators)]);
    state.humanitarianIndicators = humanitarianIndicators.localities; state.humanitarianIndicatorsMeta = humanitarianIndicators.sources; idpMaximum = Math.max(...Object.values(state.humanitarianIndicators).map(record => record.idps || 0), 1);
    localities.features.forEach(feature => { const population = populationOverrides.populations[feature.properties.hrpcode]; if (population) { feature.properties.total_pop = population; feature.properties.population_source = populationOverrides.source; } });
    state.geziraGeometries = localities.features.filter(feature => isGezira(feature.properties.state_en)).map(feature => feature.geometry);
    localityPopulationMaximum = Math.max(...localities.features.filter(feature => isKnownState(feature.properties.state_en)).map(feature => number(feature.properties.total_pop)), 1);
    localities.features.filter(feature => isKnownState(feature.properties.state_en)).forEach(feature => { const key = stateGroupKey(feature.properties.state_en); if (!key) return; statePopulationMaximums[key] = Math.max(statePopulationMaximums[key] || 1, number(feature.properties.total_pop)); stateTotalPopulations[key] = (stateTotalPopulations[key] || 0) + number(feature.properties.total_pop); });
    const healthRows = parseCsv(healthCsv); const waterRows = parseCsv(waterCsv); state.health = healthRows.map(row => ({ name: row.name, state: row.level2, locality: row.level3, latitude: coordinate(row.latitude), longitude: coordinate(row.longitude) })).filter(record => validPoint(record.latitude, record.longitude)); state.water = waterRows.map(row => ({ id: row['Project ID'], name: row['Sub-Project Name'] || row['Project Name'], donor: row.Donor, state: row.State, locality: row.Locality, beneficiaries: number(row['Approx. Beneficiaries']), latitude: coordinate(row.Latitude), longitude: coordinate(row.Longitude) })).filter(record => validPoint(record.latitude, record.longitude)); state.quality.healthInvalid = healthRows.length - state.health.length; state.quality.waterInvalid = waterRows.length - state.water.length;
    state.localities = localities; state.metadata = metadata; state.authoritySchools = authoritySchools; populateStateFilter(); populateLocalityFilter(); document.querySelector('#search-filter').value = state.search; document.querySelector('#choropleth-select').value = state.choroplethMode; updateChoroplethScale(); document.querySelector('#locality-overlay-toggle').checked = state.labelsVisible; layers.localities.addData(localities); Object.values(layers).filter(Boolean).filter(layer => layer !== layers.schools).forEach(layer => map.addLayer(layer)); map.addLayer(layers.schools); if (!state.labelsVisible) layers.localities.eachLayer(layer => layer.closeTooltip()); selectedLocalities().forEach(feature => layers.localityHighlight.addData(feature));
    await Promise.all([loadSchools(), loadReferenceLayer('educationReference'), loadReferenceLayer('waterReference')]); updateDashboard(); fitResults(); document.querySelector('#data-status').textContent = `${t('updated')} · ${metadata.lastDataReview}`; document.querySelector('#map-loading').classList.add('hidden');
  } catch (error) { document.querySelector('#map-loading').classList.add('hidden'); showError(error); }
}

function updateChoroplethScale() {
  const label = document.querySelector('#choropleth-scale-label'); const gradient = document.querySelector('#choropleth-scale i');
  if (state.choroplethMode === 'severity') { label.textContent = t('needsSeverity'); gradient.style.background = 'linear-gradient(90deg, hsl(8 30% 92%), hsl(8 90% 47%))'; }
  else if (state.choroplethMode === 'idps') { label.textContent = t('idps'); gradient.style.background = 'linear-gradient(90deg, hsl(35 30% 92%), hsl(35 90% 47%))'; }
  else { label.textContent = t('reportedPopulation'); gradient.style.background = 'linear-gradient(90deg, hsl(204 26% 94%), hsl(204 96% 46%))'; }
}
document.querySelectorAll('[data-layer]').forEach(input => input.addEventListener('change', event => { setLayerVisibility(event.target.dataset.layer, event.target.checked); updateUrl(); }));
document.querySelector('#locality-overlay-toggle').addEventListener('change', event => { const visible = event.target.checked; setLayerVisibility('localities', visible); setLabelVisibility(visible); updateUrl(); });
document.querySelector('#choropleth-select').addEventListener('change', event => { state.choroplethMode = event.target.value; layers.localities.setStyle(localityStyle); updateChoroplethScale(); updateUrl(); });
document.querySelector('#search-filter').addEventListener('input', event => { state.search = event.target.value; updateDashboard(); });
document.querySelectorAll('[data-language]').forEach(button => button.addEventListener('click', () => setLanguage(button.dataset.language)));
document.querySelector('#theme-toggle').addEventListener('change', event => setTheme(event.target.checked ? 'dark' : 'light'));
document.querySelector('#help-button').addEventListener('click', () => document.querySelector('#help-dialog').showModal());
document.querySelectorAll('.dialog-close').forEach(button => button.addEventListener('click', () => document.querySelector('#help-dialog').close()));
document.querySelector('#share-view').addEventListener('click', shareView);
document.querySelector('#print-dashboard').addEventListener('click', () => print());
document.querySelector('#fit-results').addEventListener('click', fitResults); document.querySelector('#reset-map').addEventListener('click', () => map.setView([15.4, 33.2], 6));
setLanguage(localStorage.getItem('gezira-dashboard-language') || 'en');
init();