const ASSETS = {
  health: 'Geo Assets/Al_health_facilities.csv',
  water: 'Geo Assets/All_water_Projects.csv',
  schools: 'Geo Assets/Schools.json',
  localities: 'Geo Assets/Sudan_Localities/Sudan_Khartoum_Localities.geojson',
  populationOverrides: 'Geo Assets/Sudan_Localities/population_overrides.json',
  metadata: 'metadata.json',
  authoritySchools: 'Geo Assets/External/schools-authority-gezira.json',
  educationReference: 'Geo Assets/External/hotosm-education-gezira.geojson',
  waterReference: 'Geo Assets/External/hotosm-water-reference-gezira.geojson'
};

const urlState = new URLSearchParams(location.search);
const state = { health: [], water: [], schools: [], authoritySchools: [], educationReference: [], waterReference: [], localities: null, metadata: null, geziraGeometries: [], selectedLocalityCode: urlState.get('locality') || 'all', search: urlState.get('search') || '', schoolLoaded: false, educationReferenceLoaded: false, waterReferenceLoaded: false, labelsVisible: urlState.get('labels') !== 'false', quality: { healthInvalid: 0, waterInvalid: 0, schoolsOutside: 0 }, language: 'en' };
const layers = {};
let localityPopulationMaximum = 1;
const extendedTranslations = { en: { localityLabels: 'Locality labels', educationReference: 'Education reference (HOT/OSM)', waterReference: 'Water infrastructure reference (HOT/OSM)', hotOsm: 'Humanitarian OpenStreetMap Team / OpenStreetMap', authoritySchools: 'Authority school records', students: 'Students enrolled', search: 'Search facilities and projects', searchPlaceholder: 'Search by name or ID', localityProfile: 'Locality profile', facilityRate: 'Health facilities per 10,000', allLocalitiesProfile: 'All Al Gezira localities', dataQuality: 'Data quality', invalidCoordinates: 'records excluded for invalid coordinates', export: 'Export CSV', share: 'Share view', print: 'Print', shared: 'Share link copied' }, ar: { localityLabels: 'تسميات المحليات', educationReference: 'مرجع مرافق التعليم (HOT/OSM)', waterReference: 'مرجع البنية التحتية للمياه (HOT/OSM)', hotOsm: 'فريق OpenStreetMap الإنساني / OpenStreetMap', authoritySchools: 'سجلات المدارس الرسمية', students: 'الطلاب المسجلون', search: 'البحث في المرافق والمشاريع', searchPlaceholder: 'ابحث بالاسم أو المعرف', localityProfile: 'ملف المحلية', facilityRate: 'مرافق صحية لكل 10,000', allLocalitiesProfile: 'كل محليات الجزيرة', dataQuality: 'جودة البيانات', invalidCoordinates: 'سجل مستبعد لإحداثيات غير صالحة', export: 'تصدير CSV', share: 'مشاركة العرض', print: 'طباعة', shared: 'تم نسخ رابط المشاركة' } };
const dataQualityText = { en: { invalid: 'invalid-coordinate records excluded', outside: 'school records outside Al Gezira excluded' }, ar: { invalid: 'سجلات مستبعدة لإحداثيات غير صالحة', outside: 'سجلات مدارس خارج الجزيرة مستبعدة' } };
const translations = {
  en: { intelligence: 'Facilities intelligence', title: 'Gezira Facilities Dashboard', dark: 'Dark', healthFacilities: 'Health facilities', waterProjects: 'Water projects', schools: 'Schools', availableEstimates: 'From available estimates', explore: 'Explore', mapLayers: 'Map layers', displayedLayers: 'Displayed layers', localityBoundaries: 'Locality boundaries', loadsOnDemand: 'loads on demand', localityFilter: 'Locality', allLocalities: 'All Al Gezira localities', legend: 'Legend', healthFacility: 'Health facility', waterProject: 'Water project', school: 'School', localityBoundary: 'Locality boundary', reportedPopulation: 'Reported population', populationNotReported: 'Population not reported', low: 'Low', high: 'High', facilityCoverage: 'Facility coverage', fitResults: 'Fit results', mappedFacilities: 'Mapped facilities', mappedProjects: 'Mapped projects', enableSchools: 'Enable layer to load', schoolsWithin: 'Within Al Gezira localities', state: 'State', locality: 'Locality', projectId: 'Project ID', donor: 'Donor', estimatedBeneficiaries: 'Estimated beneficiaries', city: 'City', operator: 'Operator', capacity: 'Capacity', population: 'Population', notReported: 'Not reported', updated: 'Updated from source files', dataSources: 'Data sources', healthPillar: 'Health Pillar', rrPillar: 'R&R Pillar', gisUnit: 'GIS Unit data assets', populationSource: 'UNFPA / HDX, 2024', results: (health, water) => `${health.toLocaleString()} health facilities and ${water.toLocaleString()} water projects in view` },
  ar: { intelligence: 'معلومات المرافق', title: 'لوحة مرافق الجزيرة', dark: 'داكن', healthFacilities: 'المرافق الصحية', waterProjects: 'مشاريع المياه', schools: 'المدارس', availableEstimates: 'من التقديرات المتاحة', explore: 'استكشاف', mapLayers: 'طبقات الخريطة', displayedLayers: 'الطبقات المعروضة', localityBoundaries: 'حدود المحليات', loadsOnDemand: 'تحميل عند الطلب', localityFilter: 'المحلية', allLocalities: 'كل محليات الجزيرة', legend: 'المفتاح', healthFacility: 'مرفق صحي', waterProject: 'مشروع مياه', school: 'مدرسة', localityBoundary: 'حدود المحلية', reportedPopulation: 'السكان المبلغ عنهم', populationNotReported: 'بيانات السكان غير متاحة', low: 'منخفض', high: 'مرتفع', facilityCoverage: 'تغطية المرافق', fitResults: 'ملاءمة العرض', mappedFacilities: 'مرافق محددة على الخريطة', mappedProjects: 'مشاريع محددة على الخريطة', enableSchools: 'فعّل الطبقة للتحميل', schoolsWithin: 'ضمن محليات الجزيرة', state: 'الولاية', locality: 'المحلية', projectId: 'معرف المشروع', donor: 'الجهة المانحة', estimatedBeneficiaries: 'المستفيدون التقديريون', city: 'المدينة', operator: 'المشغل', capacity: 'السعة', population: 'السكان', notReported: 'غير متاح', updated: 'تم التحديث من ملفات المصدر', dataSources: 'مصادر البيانات', healthPillar: 'ركيزة الصحة', rrPillar: 'ركيزة التعافي والقدرة على الصمود', gisUnit: 'أصول بيانات وحدة نظم المعلومات الجغرافية', populationSource: 'صندوق الأمم المتحدة للسكان / HDX، 2024', results: (health, water) => `${health.toLocaleString()} مرفقاً صحياً و${water.toLocaleString()} مشروع مياه في العرض` }
};
function t(key) { return translations[state.language][key] || extendedTranslations[state.language][key] || key; }
const map = L.map('map', { preferCanvas: true, zoomControl: false }).setView([15.4, 33.2], 6);
L.control.zoom({ position: 'bottomright' }).addTo(map);
const baseMap = L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Light_Gray_Base/MapServer/tile/{z}/{y}/{x}', { maxZoom: 16, attribution: 'Tiles &copy; Esri' }).addTo(map);
const baseMapUrls = { light: 'https://server.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Light_Gray_Base/MapServer/tile/{z}/{y}/{x}', dark: 'https://server.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Dark_Gray_Base/MapServer/tile/{z}/{y}/{x}' };

function updateUrl() { const query = new URLSearchParams(); if (state.selectedLocalityCode !== 'all') query.set('locality', state.selectedLocalityCode); if (state.search) query.set('search', state.search); if (!state.labelsVisible) query.set('labels', 'false'); history.replaceState(null, '', `${location.pathname}${query.size ? `?${query}` : ''}`); }
function setTheme(theme) { document.documentElement.dataset.theme = theme; document.querySelector('#theme-toggle').checked = theme === 'dark'; baseMap.setUrl(baseMapUrls[theme]); localStorage.setItem('gezira-dashboard-theme', theme); }
const preferredTheme = localStorage.getItem('gezira-dashboard-theme') || (matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light');
setTheme(preferredTheme);
function setLanguage(language) { state.language = language; document.documentElement.lang = language; document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr'; document.querySelectorAll('[data-i18n]').forEach(element => { element.textContent = t(element.dataset.i18n); }); document.querySelector('#search-filter').placeholder = t('searchPlaceholder'); document.querySelectorAll('[data-language]').forEach(button => button.classList.toggle('active', button.dataset.language === language)); if (state.localities) { populateLocalityFilter(); layers.localities.clearLayers(); layers.localities.addData(state.localities); updateDashboard(); document.querySelector('#data-status').textContent = t('updated'); } localStorage.setItem('gezira-dashboard-language', language); }

function parseCsv(text) {
  const rows = []; let row = []; let value = ''; let quoted = false;
  for (let index = 0; index < text.length; index += 1) {
    const character = text[index];
    if (character === '"') { if (quoted && text[index + 1] === '"') { value += character; index += 1; } else quoted = !quoted; }
    else if (character === ',' && !quoted) { row.push(value.trim()); value = ''; }
    else if ((character === '\n' || character === '\r') && !quoted) { if (character === '\r' && text[index + 1] === '\n') index += 1; row.push(value.trim()); if (row.some(Boolean)) rows.push(row); row = []; value = ''; }
    else value += character;
  }
  if (value || row.length) { row.push(value.trim()); rows.push(row); }
  const [headers, ...records] = rows;
  return records.map(record => Object.fromEntries(headers.map((header, index) => [header, record[index] ?? ''])));
}

function coordinate(value) { const parsed = Number.parseFloat(String(value).replace(',', '.')); return Number.isFinite(parsed) ? parsed : null; }
function validPoint(latitude, longitude) { return latitude !== null && longitude !== null && Math.abs(latitude) <= 90 && Math.abs(longitude) <= 180; }
function number(value) { return Number.parseFloat(String(value || '').replace(/,/g, '')) || 0; }
function safe(value) { const node = document.createElement('span'); node.textContent = value || 'Not available'; return node.innerHTML; }
function normalizedName(value) { return String(value || '').toLocaleLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[\u064B-\u065F\u0670]/g, '').replace(/[^\p{L}\p{N}]/gu, ''); }
function isGezira(value) { return /gezira|gazira|jazeera|jazirah|الجزيرة/i.test(value || ''); }
function pointInRing(longitude, latitude, ring) { let inside = false; for (let index = 0, previous = ring.length - 1; index < ring.length; previous = index, index += 1) { const [currentLongitude, currentLatitude] = ring[index]; const [previousLongitude, previousLatitude] = ring[previous]; const intersects = (currentLatitude > latitude) !== (previousLatitude > latitude) && longitude < ((previousLongitude - currentLongitude) * (latitude - currentLatitude)) / (previousLatitude - currentLatitude) + currentLongitude; if (intersects) inside = !inside; } return inside; }
function pointInPolygon(longitude, latitude, polygon) { return pointInRing(longitude, latitude, polygon[0]) && !polygon.slice(1).some(ring => pointInRing(longitude, latitude, ring)); }
function isWithinGeziraLocality(longitude, latitude) { return state.geziraGeometries.some(geometry => geometry.type === 'Polygon' ? pointInPolygon(longitude, latitude, geometry.coordinates) : geometry.type === 'MultiPolygon' && geometry.coordinates.some(polygon => pointInPolygon(longitude, latitude, polygon))); }
function selectedLocality() { return state.localities?.features.find(feature => feature.properties.hrpcode === state.selectedLocalityCode); }
function isWithinSelectedLocality(longitude, latitude) { const feature = selectedLocality(); if (!feature) return true; return feature.geometry.type === 'Polygon' ? pointInPolygon(longitude, latitude, feature.geometry.coordinates) : feature.geometry.coordinates.some(polygon => pointInPolygon(longitude, latitude, polygon)); }
function populateLocalityFilter() { const select = document.querySelector('#locality-filter'); const features = state.localities.features.filter(feature => isGezira(feature.properties.state_en)); select.replaceChildren(new Option(t('allLocalities'), 'all'), ...features.map(feature => new Option(state.language === 'ar' ? feature.properties.loc_name : feature.properties.loc_en, feature.properties.hrpcode))); select.value = state.selectedLocalityCode; }
function matchesSearch(record) { const query = state.search.trim().toLocaleLowerCase(); return !query || [record.name, record.id, record.state, record.locality, record.donor].filter(Boolean).join(' ').toLocaleLowerCase().includes(query); }
function localityStyle(feature) { const selected = feature.properties.hrpcode === state.selectedLocalityCode; const population = number(feature.properties.total_pop); const outline = { color: selected ? '#006eb5' : population <= 0 ? '#89949b' : '#006eb5', weight: selected ? 3 : 1.4, dashArray: selected ? null : '5 4' }; if (population <= 0) return { ...outline, fillColor: '#e4e8eb', fillOpacity: selected ? .82 : .72 }; const ratio = Math.min(population / localityPopulationMaximum, 1); return { ...outline, fillColor: `hsl(204 ${26 + ratio * 70}% ${94 - ratio * 48}%)`, fillOpacity: selected ? .82 : .68 }; }
function markerIcon(type) { return L.divIcon({ className: '', html: `<div class="facility-marker ${type}"></div>`, iconSize: [17, 17], iconAnchor: [8, 8] }); }
function popup(type, title, fields) { return `<article class="popup-content"><p>${type}</p><h3>${safe(title)}</h3><dl>${fields.filter(([, value]) => value).map(([label, value]) => `<dt>${safe(label)}</dt><dd>${safe(value)}</dd>`).join('')}</dl></article>`; }

function createCluster(type) { return L.markerClusterGroup({ chunkedLoading: true, chunkInterval: 80, chunkDelay: 20, removeOutsideVisibleBounds: true, spiderfyOnMaxZoom: true, maxClusterRadius: 48, iconCreateFunction: cluster => { const count = cluster.getChildCount(); const size = count < 10 ? 34 : count < 100 ? 40 : 46; return L.divIcon({ html: `<div>${count}</div>`, className: `marker-cluster layer-cluster ${type}`, iconSize: [size, size] }); } }); }
function addHealthMarkers(records) { layers.health.clearLayers(); records.forEach(record => layers.health.addLayer(L.marker([record.latitude, record.longitude], { icon: markerIcon('health'), title: record.name }).bindPopup(popup(t('healthFacility'), record.name, [[t('state'), record.state], [t('locality'), record.locality]])))); }
function addWaterMarkers(records) { layers.water.clearLayers(); records.forEach(record => layers.water.addLayer(L.marker([record.latitude, record.longitude], { icon: markerIcon('water'), title: record.name }).bindPopup(popup(t('waterProject'), record.name, [[t('projectId'), record.id], [t('state'), record.state], [t('locality'), record.locality], [t('donor'), record.donor], [t('estimatedBeneficiaries'), record.beneficiaries ? record.beneficiaries.toLocaleString() : '']])))); }
function addSchoolMarkers(records) { layers.schools.clearLayers(); records.forEach(record => layers.schools.addLayer(L.marker([record.latitude, record.longitude], { icon: markerIcon('school'), title: record.name }).bindPopup(popup(t('school'), record.name, [[t('city'), record.city], [t('operator'), record.operator], [t('capacity'), record.capacity], ['School ID', record.authority?.school_id], ['Type', record.authority?.type], ['Status', record.authority?.status], ['Students', record.authority?.students_total], ['Teachers', record.authority?.teachers], ['Electricity', record.authority?.electricity], ['Water source', record.authority?.potable_water_source]])))); }
function addReferenceMarkers(layer, records, type, heading, fields) { layer.clearLayers(); records.filter(record => isWithinSelectedLocality(record.longitude, record.latitude)).forEach(record => layer.addLayer(L.marker([record.latitude, record.longitude], { icon: markerIcon(type), title: record.name }).bindPopup(popup(heading, record.name, fields(record))))); }

function filteredHealth() { return state.health.filter(record => isWithinSelectedLocality(record.longitude, record.latitude) && matchesSearch(record)); }
function filteredWater() { return state.water.filter(record => isWithinSelectedLocality(record.longitude, record.latitude) && matchesSearch(record)); }
function updateProfile(health, water, schools) { const selected = selectedLocality(); const population = selected ? number(selected.properties.total_pop) : state.localities.features.filter(feature => isGezira(feature.properties.state_en)).reduce((sum, feature) => sum + number(feature.properties.total_pop), 0); const authoritySchools = state.authoritySchools.filter(record => state.selectedLocalityCode === 'all' || record.locality_code === state.selectedLocalityCode); const educationReferences = state.educationReference.filter(record => isWithinSelectedLocality(record.longitude, record.latitude)); const waterReferences = state.waterReference.filter(record => isWithinSelectedLocality(record.longitude, record.latitude)); document.querySelector('#profile-title').textContent = selected ? (state.language === 'ar' ? selected.properties.loc_name : selected.properties.loc_en) : t('allLocalitiesProfile'); document.querySelector('#profile-population').textContent = population.toLocaleString(); document.querySelector('#profile-health').textContent = health.length.toLocaleString(); document.querySelector('#profile-water').textContent = water.length.toLocaleString(); document.querySelector('#profile-schools').textContent = state.schoolLoaded ? schools.length.toLocaleString() : '-'; document.querySelector('#profile-authority-schools').textContent = authoritySchools.length.toLocaleString(); document.querySelector('#profile-students').textContent = authoritySchools.reduce((sum, record) => sum + number(record.students_total), 0).toLocaleString(); document.querySelector('#profile-education-reference').textContent = state.educationReferenceLoaded ? educationReferences.length.toLocaleString() : '-'; document.querySelector('#profile-water-reference').textContent = state.waterReferenceLoaded ? waterReferences.length.toLocaleString() : '-'; document.querySelector('#profile-rate').textContent = population ? ((health.length / population) * 10000).toFixed(1) : '-'; const invalid = state.quality.healthInvalid + state.quality.waterInvalid; const quality = dataQualityText[state.language]; document.querySelector('#data-quality').textContent = `${t('dataQuality')}: ${invalid} ${quality.invalid}; ${state.quality.schoolsOutside} ${quality.outside}`; }
function updateDashboard() {
  const health = filteredHealth(); const water = filteredWater(); const schools = state.schoolLoaded ? state.schools.filter(record => isWithinSelectedLocality(record.longitude, record.latitude) && matchesSearch(record)) : [];
  addHealthMarkers(health); addWaterMarkers(water); if (state.schoolLoaded) addSchoolMarkers(schools);
  if (state.educationReferenceLoaded) addReferenceMarkers(layers.educationReference, state.educationReference, 'education-reference', t('educationReference'), record => [[t('locality'), record.locality], ['OSM ID', record.id], [t('city'), record.city]]);
  if (state.waterReferenceLoaded) addReferenceMarkers(layers.waterReference, state.waterReference, 'water-reference', t('waterReference'), record => [['Type', record.type], [t('locality'), record.locality], ['OSM ID', record.id]]);
  document.querySelector('#result-summary').textContent = t('results')(health.length, water.length);
  updateProfile(health, water, schools); updateUrl();
}
function setLabelVisibility(visible) { state.labelsVisible = visible; layers.localities.eachLayer(layer => visible ? layer.openTooltip() : layer.closeTooltip()); updateUrl(); }
async function shareView() { try { await navigator.clipboard.writeText(location.href); document.querySelector('#data-status').textContent = t('shared'); } catch { document.querySelector('#data-status').textContent = location.href; } }
function fitResults() { const selected = selectedLocality(); if (selected) { map.fitBounds(L.geoJSON(selected).getBounds(), { padding: [35, 35], maxZoom: 11 }); return; } const records = [...filteredHealth(), ...filteredWater(), ...(state.schoolLoaded ? state.schools : [])]; if (records.length) map.fitBounds(L.latLngBounds(records.map(record => [record.latitude, record.longitude])), { padding: [35, 35], maxZoom: 11 }); }

async function fetchAsset(path, parser = response => response.json()) { const response = await fetch(encodeURI(path)); if (!response.ok) throw new Error(`${path} could not be loaded (${response.status})`); return parser(response); }
async function loadSchools() { if (state.schoolLoaded) return; const geojson = await fetchAsset(ASSETS.schools); const authorityByName = new Map(state.authoritySchools.flatMap(record => [[normalizedName(record.name_en), record], [normalizedName(record.name_ar), record]]).filter(([name]) => name)); const points = geojson.features.map(feature => { const properties = feature.properties; const nameEn = properties.name_en || properties.name; const nameAr = properties.name_ar; const name = state.language === 'ar' && nameAr ? nameAr : nameEn || nameAr || 'Unnamed school'; return { name, nameEn, nameAr, city: properties.addr_city, operator: properties.operator_t, capacity: properties.capacity_p, authority: authorityByName.get(normalizedName(nameEn)) || authorityByName.get(normalizedName(nameAr)), latitude: feature.geometry?.coordinates?.[1], longitude: feature.geometry?.coordinates?.[0] }; }); const validPoints = points.filter(record => validPoint(record.latitude, record.longitude)); state.quality.schoolsOutside = validPoints.length - validPoints.filter(record => isWithinGeziraLocality(record.longitude, record.latitude)).length; state.schools = validPoints.filter(record => isWithinGeziraLocality(record.longitude, record.latitude)); state.schoolLoaded = true; updateDashboard(); }
async function loadReferenceLayer(name) { if (state[`${name}Loaded`]) return; const geojson = await fetchAsset(ASSETS[name]); state[name] = geojson.features.map(feature => ({ id: feature.properties.id, name: feature.properties.name_en || feature.properties.name || feature.properties.name_ar || 'Unnamed reference', locality: feature.properties.adm2_name, city: feature.properties.addr_city, type: feature.properties.man_made || feature.properties.amenity || 'Reference', latitude: feature.geometry?.coordinates?.[1], longitude: feature.geometry?.coordinates?.[0] })).filter(record => validPoint(record.latitude, record.longitude)); state[`${name}Loaded`] = true; updateDashboard(); }
function setLayerVisibility(name, visible) { if (visible) { if (name === 'schools' || name === 'educationReference' || name === 'waterReference') { map.addLayer(layers[name]); const loader = name === 'schools' ? loadSchools : () => loadReferenceLayer(name); loader().catch(showError); } else { map.addLayer(layers[name]); if (name === 'localities') map.addLayer(layers.localityHighlight); } } else { map.removeLayer(layers[name]); if (name === 'localities') map.removeLayer(layers.localityHighlight); } }
function showError(error) { document.querySelector('#data-status').textContent = 'Some data could not be loaded'; document.querySelector('#result-summary').textContent = error.message; console.error(error); }

async function init() {
  layers.health = createCluster('health'); layers.water = createCluster('water'); layers.schools = createCluster('school'); layers.educationReference = createCluster('education-reference'); layers.waterReference = createCluster('water-reference'); layers.localityHighlight = L.geoJSON(null, { interactive: false, style: { color: '#006eb5', weight: 4, opacity: 1, fillColor: '#b5d5f5', fillOpacity: .24 } }); layers.localities = L.geoJSON(null, { filter: feature => isGezira(feature.properties.state_en), style: localityStyle, onEachFeature: (feature, layer) => { const population = number(feature.properties.total_pop); const localityName = state.language === 'ar' ? feature.properties.loc_name : feature.properties.loc_en || 'Locality'; const stateName = state.language === 'ar' ? feature.properties.state : feature.properties.state_en; layer.bindPopup(popup(t('locality'), localityName, [[t('state'), stateName], [t('population'), population > 0 ? population.toLocaleString() : t('notReported')], [t('dataSources'), feature.properties.population_source ? t('populationSource') : '']])); layer.bindTooltip(`<strong>${safe(localityName)}</strong><span>${safe(stateName)}</span>`, { permanent: true, direction: 'center', className: 'locality-label' }); } });
  try {
    const [healthCsv, waterCsv, localities, populationOverrides, metadata, authoritySchools] = await Promise.all([fetchAsset(ASSETS.health, response => response.text()), fetchAsset(ASSETS.water, response => response.text()), fetchAsset(ASSETS.localities), fetchAsset(ASSETS.populationOverrides), fetchAsset(ASSETS.metadata), fetchAsset(ASSETS.authoritySchools)]);
    localities.features.forEach(feature => { const population = populationOverrides.populations[feature.properties.hrpcode]; if (population) { feature.properties.total_pop = population; feature.properties.population_source = populationOverrides.source; } });
    state.geziraGeometries = localities.features.filter(feature => isGezira(feature.properties.state_en)).map(feature => feature.geometry);
    localityPopulationMaximum = Math.max(...localities.features.filter(feature => isGezira(feature.properties.state_en)).map(feature => number(feature.properties.total_pop)), 1);
    const healthRows = parseCsv(healthCsv); const waterRows = parseCsv(waterCsv); state.health = healthRows.map(row => ({ name: row.name, state: row.level2, locality: row.level3, latitude: coordinate(row.latitude), longitude: coordinate(row.longitude) })).filter(record => validPoint(record.latitude, record.longitude)); state.water = waterRows.map(row => ({ id: row['Project ID'], name: row['Sub-Project Name'] || row['Project Name'], donor: row.Donor, state: row.State, locality: row.Locality, beneficiaries: number(row['Approx. Beneficiaries']), latitude: coordinate(row.Latitude), longitude: coordinate(row.Longitude) })).filter(record => validPoint(record.latitude, record.longitude)); state.quality.healthInvalid = healthRows.length - state.health.length; state.quality.waterInvalid = waterRows.length - state.water.length;
    state.localities = localities; state.metadata = metadata; state.authoritySchools = authoritySchools; populateLocalityFilter(); document.querySelector('#search-filter').value = state.search; document.querySelector('#labels-toggle').checked = state.labelsVisible; layers.localities.addData(localities); Object.values(layers).filter(Boolean).filter(layer => layer !== layers.schools).forEach(layer => map.addLayer(layer)); if (!state.labelsVisible) layers.localities.eachLayer(layer => layer.closeTooltip());
    updateDashboard(); fitResults(); document.querySelector('#data-status').textContent = `${t('updated')} · ${metadata.lastDataReview}`; document.querySelector('#map-loading').classList.add('hidden');
  } catch (error) { document.querySelector('#map-loading').classList.add('hidden'); showError(error); }
}

document.querySelectorAll('[data-layer]').forEach(input => input.addEventListener('change', event => { setLayerVisibility(event.target.dataset.layer, event.target.checked); updateUrl(); }));
document.querySelector('#labels-toggle').addEventListener('change', event => setLabelVisibility(event.target.checked));
document.querySelector('#locality-filter').addEventListener('change', event => { state.selectedLocalityCode = event.target.value; layers.localities.setStyle(localityStyle); layers.localityHighlight.clearLayers(); const selected = selectedLocality(); if (selected) { layers.localityHighlight.addData(selected); layers.localityHighlight.bringToFront(); } updateDashboard(); fitResults(); });
document.querySelector('#search-filter').addEventListener('input', event => { state.search = event.target.value; updateDashboard(); });
document.querySelectorAll('[data-language]').forEach(button => button.addEventListener('click', () => setLanguage(button.dataset.language)));
document.querySelector('#theme-toggle').addEventListener('change', event => setTheme(event.target.checked ? 'dark' : 'light'));
document.querySelector('#help-button').addEventListener('click', () => document.querySelector('#help-dialog').showModal());
document.querySelectorAll('.dialog-close').forEach(button => button.addEventListener('click', () => document.querySelector('#help-dialog').close()));
document.querySelector('#share-view').addEventListener('click', shareView);
document.querySelector('#print-dashboard').addEventListener('click', () => print());
document.querySelector('#fit-results').addEventListener('click', fitResults); document.querySelector('#reset-map').addEventListener('click', () => map.setView([15.4, 33.2], 6));
setLanguage(localStorage.getItem('gezira-dashboard-language') || 'en');
init();